name: ci-cd

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Install packages
        run: pip install -e .[dev]

      - name: Test with pytest
        run: pytest tests/ --cov=opengenome --cov-report=xml

      - name: Use Codecov to track coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: luhouyang/opengenome

      - name: Build documentation
        run: make html --directory docs/

  cd:
    permissions:
      id-token: write
      contents: write

    needs: ci

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
